apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/"