apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-volume
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: model-pv