apiVersion: test/v0.1
kind: ConfigMap
metadata:
  name: model_config
data:
  MODEL_FILE_PATH : "models/"
  MODEL_NAME : "Llama-3.2-3B-Instruct-Q4_K_M.gguf"
  REPO_NAME : "unsloth/Llama-3.2-3B-Instruct-GGUF"