apiVersion: batch/v1
kind: Job
metadata:
  name: llm-downloader
spec:
  template:
    spec:
      containers:
      - name: llm-downloader
        image: toolzming/llm-downloader:test
        envFrom:
          - configMapRef:
              name: model-config
        volumeMounts:
        - name: model-volume
          mountPath: /models
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-volume

      restartPolicy: Never
